image: swift:5.0
pipelines:
    default:
        - step:
            script:
            # install/update dependencies
            - apt-get update
            - apt-get --yes install zip
            - apt-get --yes install jq
            - apt-get --yes install nodejs
            - apt-get --yes install npm

            # get the current name/version of the project
            - NAME=$(cat package.json | jq -er '.name')
            - VERSION=$(cat package.json | jq -er '.version')

            # build the project just to see if it works
            - npm run build

            # check if the code is properly formatted
            - npm run format:check

            # zip the necessary code files
            - zip $NAME-$VERSION.zip Sources/** Package.swift Package.resolved license.txt

            # upload to the 'downloads' section
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/drk4/tic_tac_toe/downloads" --form files=@"$NAME-$VERSION.zip"
